name: kts

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VITE_GOOGLE_API_KEY=${VITE_GOOGLE_API_KEY}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    ports:
      - 5174:5174
