FROM node:22-alpine AS build

ARG VITE_GOOGLE_API_KEY 

WORKDIR /app

COPY package*.json .

RUN npm i

COPY . .

RUN echo "VITE_GOOGLE_API_KEY=$VITE_GOOGLE_API_KEY" > .env

CMD [ "npm", "run", "dev" ]